name: Deploy Wiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Documentation
        run: |
          pdoc --output-dir docs paradoxism

      - name: Push to Wiki
        env:  # 確保使用 GitHub Actions 的身份進行推送
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/AllanYiin/paradoxism.wiki.git
          cp -r docs/* paradoxism.wiki/
          cd paradoxism.wiki
          git add .
          git commit -m "Update wiki"
          git push
